//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecFlowHelpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecFlowHelpers.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sucursalvirtualdllo.cloudapp.net.
        /// </summary>
        public static string BaseAddress {
            get {
                return ResourceManager.GetString("BaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /chamba/Customer.
        /// </summary>
        public static string ChambaDashboard {
            get {
                return ResourceManager.GetString("ChambaDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Security/login.
        /// </summary>
        public static string ChambaLogin {
            get {
                return ResourceManager.GetString("ChambaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abc12345.
        /// </summary>
        public static string ChambaPassword {
            get {
                return ResourceManager.GetString("ChambaPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ana.ocampo@ceiba.com.co.
        /// </summary>
        public static string ChambaUser {
            get {
                return ResourceManager.GetString("ChambaUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string PinSMS {
            get {
                return ResourceManager.GetString("PinSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testing1@ceiba.com.
        /// </summary>
        public static string SignUpUserEmail {
            get {
                return ResourceManager.GetString("SignUpUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 022802339.
        /// </summary>
        public static string SignUpUserId {
            get {
                return ResourceManager.GetString("SignUpUserId", resourceCulture);
            }
        }
    }
}
